# Basic configuration
mode: 'train' # ['train', 'test']
seed: 2024
task_device: 'cuda'
max_epoch: 1024
early_stop_max: 8

# Output path & Logger
output_dir: './output/'
logger: 'none'
project_name: 'auto_run'

# Model
model_type: 'MultiVar'  # ['MultiVar', 'Stat']
model_name: ''
model_path: '' # the model parameters loaded in test phase. Setting '' is equal to '{output_dir}/model.pth'

# Dataset & Dataloader
dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/METRO_SH/METRO_SH.pkl'
# the shape of data read from .pkl is (time, dim1, dim2),
# set data mode to change the shape
# - 0: (time, dim1*dim2, 1)
# - 1: (time, dim1, 1) * dim2
# - 2: (time, dim2, 1) * dim1
data_mode: 0
batch_size: 64
his_len:  96
pred_len: 12
normalizer: 'std' # ['none', 'std']
test_ratio: 0.1
valid_ratio: 0.1

# Evaluation
evaluator_verbose: false
metrics_list:
  - mae
  - rmse
  - mape
  - smape
  # - pcc

metrics_thres: {}