# Basic configuration
mode: 'train' # ['train', 'test']
seed: 2024
task_device: 'cuda'
max_epoch: 1024
early_stop_max: 16
early_stop_start_epoch: 10
debug: false

# Output path & Logger
output_dir: './output/'
logger: 'none'
project_name: 'auto_run'

# Model
model_type: 'MultiVar'  # ['MultiVar', 'Stat']
model_name: ''
model_path: '' # the model parameters loaded in test phase. Setting '' is equal to '{output_dir}/model.pth'

# Dataset & Dataloader
dataset_pkl: '/nas/datasets/Tensor-Time-Series-Dataset/Processed_Data/ETT_hour/ETT_hour.pkl'
# the shape of data read from .pkl is (T, N, M),
# set data mode to change the shape
# - 0: Channel-Modality-Mixing      (T, NxM, 1)       (Train one model)
# - 1: Channel-Modality-Independent (T x N x M, 1, 1) (Train one model)
# - 2: Modality-Independent         (T x M, N)        (Trian one model)
# - 3: Modality-Individual          (T, N) x M        (Train M models)
data_mode: 0
batch_size: 64
his_len:  96    # input length, if lag_input is not empty, this parameter is invalid
pred_len: 12    # output length
lag_input: []   # [trend, period, closeness], set [] to use hie_len
normalizer: 'std' # ['none', 'std']
test_ratio: 0.1
valid_ratio: 0.1

# Optimizer
lr_finder: false  # whether to use lr_finder to set the lr automatically
lr: '1e-3'        # string, set '' to use default lr
eps: '1e-8'       # string, set '' to use default eps
weight_decay: '0' # string, set '' to use default weight_decay

# Scheduler
scheduler: 'None' # ['None', 'MultiStepLR', 'ExponentialLR', 'ReduceLROnPlateau', 'CosineAnnealingLR', 'CosineAnnealingWarmRestarts']

# Evaluation
evaluator_verbose: false
metrics_list:
  - mae
  - rmse
  - mape
  - smape
  - mase
  - rmsse
  - r_square
  # - pcc

metrics_thres: {}