# Basic configuration
mode: 'train' # ['train', 'test']
seed: 2024
task_device: 'cuda'
max_epoch: 1024
early_stop_max: 16

# Output path & Logger
output_dir: './output/'
logger: 'none'
project_name: 'auto_run'

# Model
model_type: 'Tensor'  # ['Tensor', 'Stat']
model_name: 'NET3_MLP'
model_path: '' # the model parameters loaded in test phase. Setting '' will turn to '{output_dir}/model.pth'

# Dataset & Dataloader
dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/METRO_SH/METRO_SH.pkl'
# the shape of data read from .pkl is (time, dim1, dim2),
# set data mode to change the shape
# - 0: (time, dim1, dim2)
# - 1: (time, dim2, dim1)
# - 2: (time, dim1*dim2, 1)
data_mode: 0
batch_size: 64
his_len:  16
pred_len: 12
normalizer: 'std' # ['none', 'std']
graph_init: 'pearson'  # ['pearson', 'invers_pearson', 'random', 'cosine']
test_ratio:  0.1
valid_ratio: 0.1

# Evaluation
evaluator_verbose: false
metrics_list:
  - mae
  - rmse
  - mape
  - smape
  - mase
  - rmsse
  # - pcc

metrics_thres: {}

