# Basic configuration
mode: 'train' # ['train', 'test']
seed: 2024
task_device: 'cuda'
max_epoch: 1024
early_stop_max: 32

# Output path & Logger
output_dir: './output/'
logger: 'none'
project_name: 'AutoTest_NYC_Bike_16_3'

# Model
model_type: 'MultiVar'  # ['Tensor', 'MultiVar']
model_name: 'CrossFormer'
model_path: '' # the model parameters loaded in test phase. Setting '' will turn to '{output_dir}/model.pth'

# Dataset & Dataloader
# dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/data/Processed_Data/JONAS_NYC_taxi/JONAS_NYC_taxi.pkl'
dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/JONAS_NYC_bike/JONAS_NYC_bike.pkl'
# dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/Metr-LA/Metr-LA.pkl'
# dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/temp/GRML_datta.pkl'
# the shape of data read from .pkl is (time, dim1, dim2),
# set data mode to change the shape
# - 0: (time, dim1, dim2)
# - 1: (time, dim2, dim1)
# - 2: (time, dim1*dim2, 1)
data_mode: 0
batch_size: 16
his_len:  16
pred_len: 3
normalizer: 'std' # ['none', 'std']
test_ratio:  0.1
valid_ratio: 0.1

# Evaluation
evaluator_verbose: false
metrics_list:
  - mae
  - rmse
  # - trunc_rmse
  - mape
  # - trunc_mape
  # - smape
  # - trun_smape
  # - masked_rmse
  # - masked_mae
  # - masked_mape

metrics_thres: {}

