# Basic configuration
mode: 'train' # ['train', 'test']
seed: 2024
task_device: 'cuda'
max_epoch: 1024
early_stop_max: 16
early_stop_start_epoch: 10
debug: false

# Output path & Logger
output_dir: './output/'
logger: 'none'
project_name: 'auto_run'

# Model
model_type: 'Tensor'  # ['Tensor', 'Stat']
model_name: 'NET3_MLP'
model_path: '' # for test only, load model paramters from this path

# Dataset & Dataloader
dataset_pkl: '/home/zhuangjiaxin/workspace/Tensor-Time-Series/Tensor-Time-Series/datasets/Tensor-Time-Series-Dataset/Processed_Data/METRO_SH/METRO_SH.pkl'
# the shape of data read from .pkl is (time, dim1, dim2),
# set data mode to change the shape
# - 0: (time, dim1, dim2)
# - 1: (time, dim2, dim1)
# - 2: (time, dim1*dim2, 1)
data_mode: 0
batch_size: 64
his_len:  96
pred_len: 12
normalizer: 'std' # ['none', 'std']
graph_init: 'pearson'  # ['pearson', 'invers_pearson', 'random', 'cosine', 'unit']
test_ratio:  0.1
valid_ratio: 0.1

# Optimizer
lr_finder: false  # whether to use lr_finder to set the lr automatically
lr: '1e-3'          # string, set '' to use default lr
eps: '1e-8'         # string, set '' to use default eps
weight_decay: '0'   # string, set '' to use default weight_decay

# Scheduler (stay tuned...)
scheduler: 'None' # ['None', 'MultiStepLR', 'MultiStepLR', 'ExponentialLR', 'ReduceLROnPlateau']

# Evaluation
evaluator_verbose: false
metrics_list:
  - mae
  - rmse
  - mape
  - smape
  - mase
  - rmsse
  - r_square
  # - pcc

metrics_thres: {}

