batch_size: 64
data_mode: 0
dataset_pkl: ./datasets/Processed_Data/JONAS_NYC_taxi/JONAS_NYC_taxi.pkl
early_stop_max: 8
evaluator_verbose: false
graph_init: pearson
his_len: 96
logger: none
max_epoch: 1024
metrics_list:
- mae
- rmse
- mape
- smape
metrics_thres: {}
mode: train
model_name: NET3_MLP
model_path: ''
model_type: NET3
normalizer: std
output_dir: checkpoints
pred_len: 12
project_name: 96_12_NET3_JONAS_NYC_taxi
seed: 2024
task_device: cuda
test_ratio: 0.1
valid_ratio: 0.1
